apiVersion: v1
kind: Pod
metadata:
  name: var-ejemplo
  labels:
    app: variables
spec:
  containers:
    - name: contenedor-variables
      image: gcr.io/google-samples/node-hello:1.0
      env:
        - name: NAME
          value: "Formaci√≥n Kubernetes"
        - name: OWNER
          value: "Sergio"
